from typing import Dict, List, Set

CANONICAL_SKILLS: Dict[str, str] = {
    # Engineering & Backend
    "Python": "Engineering",
    "Java": "Engineering",
    "JavaScript": "Engineering",
    "TypeScript": "Engineering",
    "Node.js": "Engineering",
    "FastAPI": "Engineering",
    "Django": "Engineering",
    "Flask": "Engineering",
    "PostgreSQL": "Data & Databases",
    "MongoDB": "Data & Databases",
    "Redis": "Data & Databases",
    "GraphQL": "Engineering",
    "REST API Development": "Engineering",
    "Microservices Architecture": "Architecture",
    "System Design": "Architecture",
    # Cloud & DevOps
    "Docker": "DevOps",
    "Kubernetes": "DevOps",
    "AWS": "Cloud",
    "Azure": "Cloud",
    "GCP": "Cloud",
    "CI/CD Pipelines": "DevOps",
    "Terraform": "DevOps",
    "Linux": "DevOps",
    "Cloud Infrastructure": "Cloud",
    # Data & AI
    "Machine Learning": "AI/ML",
    "Data Science": "Data",
    "Deep Learning": "AI/ML",
    "PyTorch": "AI/ML",
    "TensorFlow": "AI/ML",
    "SQL": "Data & Databases",
    "Data Engineering": "Data",
    "NLP": "AI/ML",
    "GenAI": "AI/ML",
    # Frontend
    "React": "Frontend",
    "Vue.js": "Frontend",
    "Angular": "Frontend",
    "HTML/CSS": "Frontend",
    "Frontend Architecture": "Frontend",
    "Next.js": "Frontend",
    # Business & Soft Skills
    "Agile Methodology": "Management",
    "Project Management": "Management",
    "Team Leadership": "Leadership",
    "Product Management": "Management",
    "System Architecture": "Architecture",
}

SKILL_ALIASES: Dict[str, str] = {
    "py": "Python",
    "js": "JavaScript",
    "ts": "TypeScript",
    "reactjs": "React",
    "react.js": "React",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "k8s": "Kubernetes",
    "kube": "Kubernetes",
    "aws": "AWS",
    "amazon web services": "AWS",
    "node": "Node.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "fastapi": "FastAPI",
    "ml": "Machine Learning",
    "ai": "GenAI",
    "rest": "REST API Development",
    "rest api": "REST API Development",
    "restful api": "REST API Development",
    "docker": "Docker",
    "tf": "TensorFlow",
    "pytorch": "PyTorch",
    "agile": "Agile Methodology",
    "scrum": "Agile Methodology",
    "leadership": "Team Leadership",
}
